### ISSUE TITLE
 Review the APIs which are targeting "stable" maturity in the Fall24 meta-release

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/Commonalities#266]
**Problem description**
Review the stable APIs and their compliance to Commonalities, especially on topics beyond the basis checks, such as API abuse topic, common data types usage, or other. 
Request following TSC meeting of 2024-08-01.

**Expected action**
Review the 5 APIs targeting stable public release. The APIs are here: see https://wiki.camaraproject.org/x/cgB0AQ (click twice on the targeted maturity column to sort the table with stable APIs at the top of the list).

- if you have a comment: create an issue in the Sub Project: "Commonalities review" and link it to the review issue in release management for that Sub Project repo
- if you have no comments: put a comment "Reviewed by Commonalities" in the review issue in release management for that Sub Project repo.

Additional actions:
Please complete the RM release PR review guidelines for items that are not listed there (see link below).
Also create a Commonalities issues if you see that additional linting rules can be created to automate the checks (e.g. a check that schemas are aligned with Commonalities common_data.md

**Additional context**
Current checks done by the RM team are described here: https://wiki.camaraproject.org/x/UwESAg

**Comment by hdamker** [comment]
> * if you have no comments: put a comment "Reviewed by Commonalities" in the review issue in release management for that Sub Project repo.

The review issue for M3 (release candidates) are already closed, there will be new ones for the M4 release PRs. Therefore: please do your review based on the pre-releases and add your comments preliminary here (cf. [IdentityAndConsentManagement](https://github.com/camaraproject/IdentityAndConsentManagement/issues/189 as example). We will pick the results in course of the reviews of M4 release PRs.

**Comment by PedroDiez** [comment]
Will be reviewing 3 APIs:
- SIM-SWAP
- OTP Validaton
- Location Verification

**Comment by PedroDiez** [comment]
**Commonalities Review - Sim Swap - sim-swap v1.0.0**

Ref: https://github.com/camaraproject/SimSwap/releases/tag/r1.1

- [] API definition files (YAML) review

> - [**OK**] Actions taken
> Info object: remove contact and termsOfService - [SIM-SWAP#143](https://github.com/camaraproject/SimSwap/pull/143)
> NOTES for public Release: 
> >- Adapt servers object for public release
> >- Consider 401 AUTHENTICATION_REQUIRED exception


- [ ] test file(s) availability
> - [**OK**] 
> https://github.com/camaraproject/SimSwap/tree/main/code/Test_definitions


- [ ] changelog updated
> - [**OK**]. Consider the update actions for public release


- [ ] readme updated (enforce correct release number / API version naming)
> - [**OK**]. Consider the update actions for public release

- [ ] API readiness checklist(s)
> - [**OK** ] 

cc @fernandopradocabrillo, @bigludo7

**Comment by PedroDiez** [comment]
**ICM Review - Device Location - location-verification v1.0.0**

Ref: https://github.com/camaraproject/DeviceLocation/releases/tag/r1.1

- [x] API definition files (YAML) review

> - [**OK**] NOTES for public Release: 
> - Adapt servers object and version property for public release


- [x] test file(s) availability
> - [**OK**] 


- [x] changelog updated
> - [**OK**]. Consider the update actions for public release


- [x] readme updated (enforce correct release number / API version naming)
> - [**OK**]. Consider the update actions for public release


- [x] API readiness checklist(s)
> - [**NOK**] Please move for public release [User stories](https://github.com/camaraproject/DeviceLocation/blob/main/documentation/SupportingDocuments/Location_Verification_User_Story.md) to "documentation/API_documentation" folder and also update API readiness checkllist (Nr 6) 


cc @jlurien, @bigludo7, @maxl2287

**Comment by rartych** [comment]
**Commonalities Review - Number Verification - number_verification v1.0.0**

https://github.com/camaraproject/NumberVerification/pull/139

- [ ] API definition files (YAML) review




- [ ] test file(s) availability



- [ ] changelog updated


- [ ] readme updated (enforce correct release number / API version naming)



- [ ] API readiness checklist(s)

**Comment by rartych** [comment]
**Commonalities Review -  Simple Edge Discovery  - simple-edge-discovery v1.0.0**

https://github.com/camaraproject/SimpleEdgeDiscovery/pull/41

- [ ] API definition files (YAML) review




- [ ] test file(s) availability



- [ ] changelog updated


- [ ] readme updated (enforce correct release number / API version naming)



- [ ] API readiness checklist(s)

**Comment by rartych** [comment]
**Commonalities Review -  of test definitions**


- [x] OTP Validation: 
  -  https://github.com/camaraproject/OTPValidation/issues/82

- [x] SimSwap 
  - https://github.com/camaraproject/SimSwap/issues/149

- [x] Location Verification
  -  https://github.com/camaraproject/DeviceLocation/issues/253

- [x] Number Verification
  - https://github.com/camaraproject/NumberVerification/issues/143

- [x] Simple Edge Discovery
  - [x] No issues

**Comment by jlurien** [comment]
> **Commonalities Review - Number Verification - number_verification v1.0.0**
> 
> [camaraproject/NumberVerification#139](https://github.com/camaraproject/NumberVerification/pull/139)
> 
> * [ ]  API definition files (YAML) review
> 
> > * [**OK**] In the path: section there is X-Correlator, the guideline was changed to use x-correlator (lower case) [Public Release for Fall24 meta-release NumberVerification#139 (comment)](https://github.com/camaraproject/NumberVerification/pull/139#issuecomment-2321039827)


@rartych could you please formally update the checklist above, as it seems that issue is resolved. Thanks

**Comment by rartych** [comment]
As the meta-release is published the issues can be closed
